import {chromium} from 'playwright';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const minutes=20,url=process.env.GRENLAND_TEST_URL??'http://127.0.0.1:4175/play/grenland/myhra';
const browser=await chromium.launch({channel:'chrome'}),context=await browser.newContext({viewport:{width:393,height:852},hasTouch:true,isMobile:true}),page=await context.newPage(),cdp=await context.newCDPSession(page),errors=[],activities=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const ready=()=>page.waitForFunction(()=>document.querySelector('.mh-swing-pad')?.disabled===false,null,{timeout:60000});
async function stroke(p){const r=await page.locator('.mh-swing-pad').boundingBox(),x=r.x+r.width*.5,y=r.y+r.height*.2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+96*p*i/8,id:1}]});await page.waitForTimeout(25);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
let started=0,buildScripts=[];
try{
 await page.goto(url);await ready();buildScripts=await page.evaluate(()=>Array.from(document.querySelectorAll('script[src]'),s=>s.src));await stroke(.65);await ready();const original=await page.evaluate(()=>localStorage.getItem('strikelab.myhra.hole.v3'));
 await page.evaluate(()=>{window.qaFrames=[];let last=performance.now();const tick=now=>{window.qaFrames.push(now-last);last=now;if(window.qaFrames.length<180000)requestAnimationFrame(tick);};requestAnimationFrame(tick);});
 started=Date.now();let cycle=0;
 while(Date.now()-started<minutes*60000){
  const action=cycle%3;
  if(action===0){await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:/Putting · 4 m/}).click();await ready();await page.getByRole('button',{name:'Use this shot',exact:false}).waitFor({timeout:20000});await page.getByRole('button',{name:'Use this shot',exact:false}).click();await stroke(Number(await page.getByLabel('Target power',{exact:true}).inputValue())/100);await page.waitForFunction(()=>document.querySelector('.mh-session-banner button')?.disabled===false,null,{timeout:30000});await page.waitForTimeout(2500);await page.getByRole('button',{name:'Return to round',exact:false}).click();await ready();}
  else if(action===1){await page.getByRole('button',{name:'Drive the cart',exact:true}).click();await page.keyboard.down('KeyW');if(cycle%2)await page.keyboard.down('Shift');await page.waitForTimeout(5500);await page.keyboard.down('KeyD');await page.waitForTimeout(1800);await page.keyboard.up('KeyD');await page.keyboard.up('KeyW');await page.keyboard.up('Shift');await page.waitForTimeout(2500);await page.keyboard.down('KeyS');await page.waitForTimeout(2000);await page.keyboard.up('KeyS');await page.getByRole('button',{name:'Back to my ball',exact:false}).click();}
  else {await page.getByRole('button',{name:'Round journal',exact:true}).click();await page.getByRole('button',{name:'Myhra replay',exact:true}).click();if(!await page.getByRole('button',{name:'Watch in 3D',exact:false}).isEnabled()){await page.getByRole('button',{name:'+ Shot',exact:true}).click();await page.getByRole('button',{name:'Use preview tee',exact:true}).click();await page.getByRole('button',{name:'Place finish',exact:true}).click();await page.locator('.gj-map').scrollIntoViewIfNeeded();const p=await page.locator('.gj-map').evaluate(s=>{const p=s.createSVGPoint();p.x=360;p.y=390;const q=p.matrixTransform(s.getScreenCTM());return{x:q.x,y:q.y};});await page.mouse.click(p.x,p.y);}await page.getByRole('button',{name:'Watch in 3D',exact:false}).click();await page.waitForTimeout(4000);await page.getByLabel('Replay progress',{exact:true}).fill('500');await page.waitForTimeout(2000);await page.getByRole('button',{name:'Close round journal',exact:true}).click();}
  await page.waitForTimeout(9000);assert.equal(await page.evaluate(()=>localStorage.getItem('strikelab.myhra.hole.v3')),original,'mixed play cannot replace the saved active round');assert.deepEqual(errors,[]);
  activities.push({seconds:Math.round((Date.now()-started)/1000),action:['putting','driving','replay'][action]});console.log('SOAK',activities.at(-1));cycle++;
 }
 const times=await page.evaluate(()=>window.qaFrames),sorted=times.slice().sort((a,b)=>a-b),quantile=q=>sorted[Math.floor((sorted.length-1)*q)];
 const result={passed:true,url,buildScripts,completedAt:new Date().toISOString(),kind:'20-minute Chrome headless mixed session, mobile viewport on available PC; not physical iPhone or DualSense',elapsedSeconds:(Date.now()-started)/1000,frames:times.length,p95Ms:quantile(.95),p99Ms:quantile(.99),activities,errors};console.log(JSON.stringify(result));await writeFile('../docs/rebuild/soak.json',JSON.stringify(result,null,2));
}catch(e){console.error(e);await writeFile('../docs/rebuild/soak.json',JSON.stringify({passed:false,elapsedSeconds:started?(Date.now()-started)/1000:0,activities,errors,error:String(e)},null,2));process.exitCode=1;}finally{await browser.close();}
