import {useEffect,useRef,useState} from 'react';
import type {Course,PracticeHole} from './engine';
import './navigation.css';

const holeURL=(hole:number)=>hole===1?'/play/grenland/myhra':`/play/grenland?hole=${Math.max(2,Math.min(18,hole))}`;
export function HoleLinks({current}:{current:number}){return <nav className="hole-links" aria-label="Hole navigation"><a aria-label="Previous hole" href={holeURL(current===1?18:current-1)}>← Previous</a><span>{String(current).padStart(2,'0')} / 18</span><a aria-label="Next hole" href={holeURL(current===18?1:current+1)}>Next →</a></nav>;}
export default function CourseMap({current,onClose}:{current:number;onClose:()=>void}){
 const [data,setData]=useState<{regions:Course['regions'];holes:PracticeHole[]}>(),[error,setError]=useState(''),dialog=useRef<HTMLElement>(null);
 useEffect(()=>{const controller=new AbortController();Promise.all(['manifest','routes'].map(async name=>{const r=await fetch(`/courses/grenland/${name}.json`,{signal:controller.signal});if(!r.ok)throw Error('The course map could not load.');return r.json();})).then(([course,routes])=>setData({regions:course.regions,holes:routes.preview})).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.querySelector('button')?.focus();const key=(e:KeyboardEvent)=>{e.stopPropagation();if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,a')??[]),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};dialog.current?.addEventListener('keydown',key);const node=dialog.current;return()=>{node?.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const all=data?.holes.flatMap(h=>[h.tee,h.pin])??[],xs=all.map(p=>p[0]),zs=all.map(p=>p[2]),minX=Math.min(...xs)-110,minZ=Math.min(...zs)-110,width=Math.max(...xs)-minX+110,height=Math.max(...zs)-minZ+110;
 return <div className="golf-map-backdrop" onClick={onClose}><section ref={dialog} className="golf-course-map" role="dialog" aria-modal="true" aria-label="Full course map" onClick={e=>e.stopPropagation()}><header><div><small>GRENLAND GOLF CLUB</small><h2>Find your next hole.</h2></div><button aria-label="Close course map" onClick={onClose}>×</button></header><HoleLinks current={current}/>{data?<div className="golf-map-content"><svg role="img" aria-label="Grenland 18 hole course overview" viewBox={`${minX} ${minZ} ${width} ${height}`}><rect x={minX} y={minZ} width={width} height={height} fill="#112b25"/>{data.regions.map(r=><polygon key={r.id} points={r.points.map(p=>p.join(',')).join(' ')} fill={r.kind==='water'?'#416e82':r.kind==='green'?'#aac47c':r.kind==='bunker'?'#d9c696':r.kind==='fairway'?'#527049':'#1b3829'}/>)}{data.holes.map((h,i)=><g key={h.name}><path d={`M ${(h.route??[[h.tee[0],h.tee[2]],[h.pin[0],h.pin[2]]]).map(p=>p.join(' ')).join(' L ')}`} stroke={i+1===current?'#f5d58f':'#d2d9c8'} strokeWidth="2" strokeDasharray="5 6" opacity=".6"/><a href={holeURL(i+1)} aria-label={`Play hole ${i+1}: ${h.name.replace(/^\d+\s*·\s*/,'')}`}><circle cx={h.tee[0]} cy={h.tee[2]} r="23" fill={i+1===current?'#e9c57d':'#f0ecdb'}/><text x={h.tee[0]} y={h.tee[2]} dominantBaseline="central" textAnchor="middle" fontSize="23" fontWeight="700" fill="#153126">{i+1}</text></a></g>)}</svg><div className="golf-hole-list">{data.holes.map((h,i)=><a key={h.name} href={holeURL(i+1)} aria-current={i+1===current?'location':undefined}><b>{String(i+1).padStart(2,'0')}</b><span>{h.name.replace(/^\d+\s*·\s*/,'')}<small>Par {h.par} · {Math.round(Math.hypot(h.pin[0]-h.tee[0],h.pin[2]-h.tee[2]))} m{i===0?' · Myhra study':''}</small></span><span>↗</span></a>)}</div></div>:<p>{error||'Loading the course…'}</p>}<footer>Explore any hole and return to your saved ball. Each hole saves separately. Myhra is the detailed visual study; holes 2–18 use the existing course preview.</footer></section></div>;
}
